### 1) Подберите скорость обучения (alpha) и количество итераций для градиентного спуска.

In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

In [2]:
def calc_mse(y, y_pred):
    """Calc mse."""
    
    err = np.mean((y - y_pred) ** 2)
    
    return err

In [3]:
y = np.array([45, 55, 50, 59, 65, 35, 75, 80, 50, 60])

X = np.array(
    [
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 2, 1, 3, 0, 5, 10, 1, 2]
    ]
)

In [4]:
n = X.shape[1]
alpha = 1e-04

W = np.array([1, 0.5])
W, alpha

(array([1. , 0.5]), 0.0001)

In [5]:
for i in range(1500):
    y_pred = W.dot(X)
    err = calc_mse(y, y_pred)
    
    for ii in range(W.shape[0]):
        W[ii] -= alpha * (1 / n * 2 * np.sum(X[ii] * (y_pred - y)))
    
    if i % 100 == 0:
        print(i, W, err)

0 [1.01102 0.534  ] 3173.15
100 [2.02168794 3.452835  ] 2207.6942101483005
200 [2.88306663 5.58962851] 1670.7027004086372
300 [3.63289519 7.14848061] 1368.0832412796256
400 [4.29908617 8.28027926] 1193.7493344933293
500 [4.90228732 9.09657298] 1089.714750358689
600 [5.45777535 9.67982684] 1024.2828984889416
700 [ 5.97685612 10.0910047 ] 980.1260644155933
800 [ 6.46789973 10.37517467] 947.770026039189
900 [ 6.93710574 10.56565326] 922.0330206910179
1000 [ 7.38906894 10.68706909] 900.0794345405571
1100 [ 7.82719761 10.75762786] 880.3560305497828
1200 [ 8.25402271 10.7907869 ] 862.0105344693482
1300 [ 8.67142649 10.79649311] 844.5738572427321
1400 [ 9.08081151 10.78209811] 827.7864098809556


In [6]:
alpha = 1e-05

In [7]:
for i in range(1500):
    y_pred = W.dot(X)
    err = calc_mse(y, y_pred)
    
    for ii in range(W.shape[0]):
        W[ii] -= alpha * (1 / n * 2 * np.sum(X[ii] * (y_pred - y)))
    
    if i % 100 == 0:
        print(i, W, err)

0 [ 9.47963242 10.75334911] 811.5031731785864
100 [ 9.51952531 10.74980549] 809.8991406600293
200 [ 9.55935717 10.74615954] 808.2992388455159
300 [ 9.59912864 10.74241452] 806.7034124068352
400 [ 9.63884035 10.73857359] 805.1116088675576
500 [ 9.67849291 10.73463981] 803.5237784368793
600 [ 9.7180869  10.73061617] 801.9398738531931
700 [ 9.75762292 10.72650554] 800.3598502368171
800 [ 9.79710151 10.72231073] 798.7836649513418
900 [ 9.83652323 10.71803445] 797.2112774730972
1000 [ 9.8758886  10.71367933] 795.6426492682525
1100 [ 9.91519814 10.70924793] 794.0777436771182
1200 [ 9.95445235 10.70474274] 792.5165258052155
1300 [ 9.99365171 10.70016616] 790.9589624207222
1400 [10.03279671 10.69552052] 789.4050218579191


In [8]:
alpha = 1e-06

In [9]:
for i in range(1500):
    y_pred = W.dot(X)
    err = calc_mse(y, y_pred)
    
    for ii in range(W.shape[0]):
        W[ii] -= alpha * (1 / n * 2 * np.sum(X[ii] * (y_pred - y)))
    
    if i % 100 == 0:
        print(i, W, err)

0 [10.07153622 10.69085079] 787.8546739262944
100 [10.07544241 10.69037598] 787.6998364086132
200 [10.07934806 10.68990054] 787.5450344988375
300 [10.08325318 10.68942445] 787.3902681690437
400 [10.08715776 10.68894772] 787.2355373914382
500 [10.09106181 10.68847036] 787.080842138356
600 [10.09496533 10.68799236] 786.9261823822596
700 [10.09886832 10.68751373] 786.7715580957387
800 [10.10277078 10.68703446] 786.6169692515089
900 [10.1066727  10.68655457] 786.462415822411
1000 [10.1105741  10.68607405] 786.3078977814107
1100 [10.11447496 10.68559291] 786.1534151015969
1200 [10.1183753  10.68511114] 785.9989677561828
1300 [10.1222751  10.68462876] 785.8445557185036
1400 [10.12617438 10.68414575] 785.6901789620159


In [10]:
alpha = 1e-07

In [11]:
for i in range(1500):
    y_pred = W.dot(X)
    err = calc_mse(y, y_pred)
    
    for ii in range(W.shape[0]):
        W[ii] -= alpha * (1 / n * 2 * np.sum(X[ii] * (y_pred - y)))
    
    if i % 100 == 0:
        print(i, W, err)

0 [10.13003804 10.68366649] 785.5358374602977
100 [10.13042788 10.68361809] 785.5204052560505
200 [10.13081773 10.68356969] 785.5049734040603
300 [10.13120756 10.68352128] 785.4895419043008
400 [10.13159739 10.68347287] 785.4741107567464
500 [10.13198722 10.68342445] 785.4586799613705
600 [10.13237704 10.68337602] 785.443249518147
700 [10.13276685 10.68332759] 785.4278194270495
800 [10.13315666 10.68327915] 785.4123896880523
900 [10.13354646 10.6832307 ] 785.3969603011285
1000 [10.13393626 10.68318225] 785.3815312662525
1100 [10.13432605 10.6831338 ] 785.3661025833981
1200 [10.13471584 10.68308533] 785.3506742525403
1300 [10.13510562 10.68303686] 785.3352462736508
1400 [10.1354954  10.68298839] 785.3198186467046


In [12]:
alpha = 1e-03

In [13]:
for i in range(1500):
    y_pred = W.dot(X)
    err = calc_mse(y, y_pred)
    
    for ii in range(W.shape[0]):
        W[ii] -= alpha * (1 / n * 2 * np.sum(X[ii] * (y_pred - y)))
    
    if i % 100 == 0:
        print(i, W, err)

0 [10.17485822 10.67809195] 785.3043913716757
100 [13.84777745 10.07185978] 646.3462742344814
200 [17.14681353  9.46603524] 533.5622516943976
300 [20.11937899  8.91728581] 441.9643152208083
400 [22.79822011  8.42262467] 367.57260561019734
500 [25.21238083  7.97683177] 307.15501655489373
600 [27.38801362  7.57508455] 258.0865775257685
700 [29.34868595  7.21303141] 218.23540593149852
800 [31.11563671  6.88675043] 185.87008294876892
900 [32.70800628  6.59270721] 159.5844283526821
1000 [34.14304394  6.32771653] 138.23640602911365
1100 [35.43629464  6.08890789] 120.89850578920918
1200 [36.60176746  5.87369442] 106.81744571850511
1300 [37.65208732  5.67974483] 95.38144424363043
1400 [38.59863174  5.50495816] 86.0936399819733


In [14]:
alpha = 1e-02

In [15]:
for i in range(1500):
    y_pred = W.dot(X)
    err = calc_mse(y, y_pred)
    
    for ii in range(W.shape[0]):
        W[ii] -= alpha * (1 / n * 2 * np.sum(X[ii] * (y_pred - y)))
    
    if i % 100 == 0:
        print(i, W, err)

0 [39.52453989  5.33398213] 78.55050454321228
100 [44.52204827  4.41115398] 49.96950478082976
200 [46.27923795  4.08667547] 46.435984048934905
300 [46.89708896  3.97258455] 45.999128485220076
400 [47.1143335   3.93246868] 45.94511924117459
500 [47.19071954  3.91836342] 45.93844198057716
600 [47.21757787  3.91340382] 45.93761645876374
700 [47.22702162  3.91165996] 45.93751439800776
800 [47.23034216  3.9110468 ] 45.93750178005174
900 [47.23150971  3.9108312 ] 45.937500220071044
1000 [47.23192023  3.91075539] 45.937500027207776
1100 [47.23206458  3.91072874] 45.93750000336375
1200 [47.23211533  3.91071937] 45.93750000041588
1300 [47.23213318  3.91071607] 45.937500000051415
1400 [47.23213945  3.91071491] 45.93750000000634


In [16]:
alpha = 1e-01

In [17]:
for i in range(1500):
    y_pred = W.dot(X)
    err = calc_mse(y, y_pred)
    
    for ii in range(W.shape[0]):
        W[ii] -= alpha * (1 / n * 2 * np.sum(X[ii] * (y_pred - y)))
    
    if i % 100 == 0:
        print(i, W, err)

0 [47.23214177  3.91071449] 45.93750000000079
100 [4.10467120e+13 2.22285467e+14] 1.8958239638766233e+29
200 [1.15559221e+44 6.25802510e+44] 1.502624511637806e+90
300 [3.25335035e+74 1.76182809e+75] 1.1909757793955625e+151
400 [9.15918993e+104 4.96009233e+105] 9.439639085621231e+211
500 [2.57859594e+135 1.39641978e+136] 7.481830244441342e+272
600 [7.25954706e+165 3.93135463e+166] inf
700 [2.04378758e+196 1.10679822e+197] inf
800 [5.75389570e+226 3.11598015e+227] inf
900 [1.61990004e+257 8.77245021e+257] inf
1000 [4.56052085e+287 2.46971672e+288] inf
1100 [nan nan] nan
1200 [nan nan] nan
1300 [nan nan] nan
1400 [nan nan] nan


<ipython-input-2-258858b316e3>:4: RuntimeWarning: overflow encountered in square
  err = np.mean((y - y_pred) ** 2)
<ipython-input-17-0ddec1e93d1d>:6: RuntimeWarning: overflow encountered in multiply
  W[ii] -= alpha * (1 / n * 2 * np.sum(X[ii] * (y_pred - y)))


* При маленьком шаге сходится очень медленно. Быстрее всего сходится при шаге alpha = 1e-02. При большом шаге, например при alpha = 1e-01, расходится.
* Для подбора количества итераций логично рассчитывать разницу весов и ошибки на предыдущих весах. Например, когда разница становится меньше заданного значения епсилон, останавливать цикл.

In [112]:
n = X.shape[1]

alpha = 1e-02

W = np.array([1, 0.5])

epsilon = 1e-4 * np.ones(W.shape[0])

W_prev = np.zeros(W.shape)

W, alpha

(array([1. , 0.5]), 0.01)

In [111]:
i = 0
while (W - W_prev > epsilon).any():
    W_prev = W.copy()
    y_pred = W.dot(X)
    err = calc_mse(y, y_pred)


    for ii in range(W.shape[0]):
        W[ii] -= alpha * (1 / n * 2 * np.sum(X[ii] * (y_pred - y)))

    i += 1

    if i % 100 == 0:
        print(i, W, err)
        
print(i, W, err)

100 [31.72648327  6.77395294] 177.92494760058068
200 [41.78014899  4.91746666] 62.25534704257841
300 [45.3151501   4.26470166] 47.95490496498403
400 [46.55810299  4.0351809 ] 46.186915427300114
500 [46.99514157  3.95447839] 45.96833568071608
600 [47.14881009  3.92610232] 45.94131227101915
700 [47.20284196  3.91612492] 45.93797131796625
800 [47.22184028  3.91261674] 45.93755826989325
808 [47.22266672  3.91246413] 45.937549296335945


### 2*) В этом коде мы избавляемся от итераций по весам, но тут есть ошибка, исправьте ее:

In [136]:
n = X.shape[1]

alpha = 1e-02

W = np.array([1, 0.5])

epsilon = 1e-4 * np.ones(W.shape[0])

W_prev = np.zeros(W.shape)

W, alpha

(array([1. , 0.5]), 0.01)

In [134]:
for i in range(287):
    y_pred = np.dot(W, X)
    
    err = calc_mse(y, y_pred)
    
    W -= (alpha * (1 / n * 2 * (X @ (y_pred - y))))
    
    if i % 10 == 0:
        print(i, W, err)

0 [47.23214286  3.91071429] 45.9375
10 [47.23214286  3.91071429] 45.9375
20 [47.23214286  3.91071429] 45.9375
30 [47.23214286  3.91071429] 45.9375
40 [47.23214286  3.91071429] 45.9375
50 [47.23214286  3.91071429] 45.9375
60 [47.23214286  3.91071429] 45.9375
70 [47.23214286  3.91071429] 45.9375
80 [47.23214286  3.91071429] 45.9375
90 [47.23214286  3.91071429] 45.9375
100 [47.23214286  3.91071429] 45.9375
110 [47.23214286  3.91071429] 45.9375
120 [47.23214286  3.91071429] 45.9375
130 [47.23214286  3.91071429] 45.9375
140 [47.23214286  3.91071429] 45.9375
150 [47.23214286  3.91071429] 45.9375
160 [47.23214286  3.91071429] 45.9375
170 [47.23214286  3.91071429] 45.9375
180 [47.23214286  3.91071429] 45.9375
190 [47.23214286  3.91071429] 45.9375
200 [47.23214286  3.91071429] 45.9375
210 [47.23214286  3.91071429] 45.9375
220 [47.23214286  3.91071429] 45.9375
230 [47.23214286  3.91071429] 45.9375
240 [47.23214286  3.91071429] 45.9375
250 [47.23214286  3.91071429] 45.9375
260 [47.23214286  3.910